Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true
  config.hostmanager.ip_resolver = proc do |vm|
    ip = `vagrant ssh #{vm.name} -c "hostname -I"`.strip.split()[0]
  end

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.synced_folder "./storage", "/vagrant/storage", owner: "vagrant", group: "vagrant"

  config.vm.define "dbpostgresql" do |db|
    db.vm.hostname = "dbpostgresql"
    db.vm.network "private_network", type: "dhcp"
    db.vm.network "forwarded_port", guest:5432 , host: 5433
    db.vm.provider "virtualbox" do |vb|
      vb.name = "database"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
  
  web_server_amount = 2

  (1..web_server_amount).each do |i|
    config.vm.define "flaskserver#{i}" do |web|
      web.vm.hostname = "flaskserver#{i}"
      web.vm.network "private_network", type: "dhcp"
      web.vm.network "forwarded_port", guest: 5000, host: 5000 + i
      web.vm.network "forwarded_port", guest: 80, host: 8100 + i
      web.vm.network "forwarded_port", guest: 8000, host: 8000 + i
      web.vm.provider "virtualbox" do |vb|
        vb.name = "webserver#{i}"
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  end

  config.vm.define "loadbalancing" do |lb|
    lb.vm.hostname = "loadbalancing"
    lb.vm.network "private_network", type: "dhcp"
    lb.vm.network "forwarded_port", guest: 80, host: 3006
    lb.vm.provider "virtualbox" do |vb|
      vb.name = "loadbalancer"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  web_servers = []
  (1..web_server_amount).each do |i|
    web_servers << "flaskserver#{i}"
  end
  config.ansible.groups = {
    'db' => ['dbpostgresql'],
    'web' => web_servers,
    'lb' => ['loadbalancing'],
  }
end




